# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'minitest', :drb => true, :notify => true do
  # with Minitest::Unit
  watch(%r|^test/(.*)\/?(.*)_test\.rb|)
  watch(%r|^lib/(.*)([^/]+)\.rb|)     { |m| "test/#{m[1]}test_#{m[2]}.rb" }
  watch(%r|^test/test_helper\.rb|)    { "test" }
  watch(%r|^test/factories\.rb|)

  # Rails 3.2
  watch(%r|^app/controllers/(.*)\.rb|) { |m| "test/controllers/#{m[1]}_test.rb" }
  watch(%r|^app/models/(.*)\.rb|)      { |m| "test/models/#{m[1]}_test.rb" }
  watch(%r|^app/controllers/application_controller\.rb|) { |m| "test/controllers/*.rb" }
  watch(%r|^app/models/base_model\.rb|) { |m| "test/controllers/*.rb" }
end
