# -*- encoding : utf-8 -*-
class SubUserMaterial
  include Mongoid::Document
  embedded_in :user
  field :name
  field :id
  field :uid
  field :tagline
  field :experiences
  field :projects
  field :summary
  field :publications
  field :skills
  field :recommendations
  field :websites
  field :interests
  field :honors_and_awards
  field :is_boy
  field :address_hometown
  field :address_now
  field :address_real
  field :school_xueshixuewei
  field :school_shuoshixuewei
  field :school_boshixuewei
  field :school_gaozhong
  field :school_zhongzhuan
  field :school_chuzhong
  field :school_xiaoxue
  field :p_xingquaihao
  field :p_xihuanyinyue
  field :p_xihuandianying
  field :p_wandeyouxi
  field :p_xihuandongman
  field :p_wandeyundong
  field :p_xihuanshuji
  field :phone_other
  field :phone_mobile
  field :im_qq
  field :im_msn
  field :im_other
  field :website_blog
  field :website_other
  field :id_type
  field :id_number
  field :birthday
  field :marital_status
  field :school
  field :astrological_sign

  field :renren_user
  field :renren_friends

  field :avatars_renren
end
